imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

sensio_framework_extra:
    view:
        annotations: false

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'
    globals:
        fos_csrf_provider: "@form.csrf_provider"
    form:
        resources:
            - ':Form:form_div_layout.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    filters:
        cssrewrite: ~
        less:
            node: node
            node_paths: [%kernel.root_dir%\..\node_modules]
            apply_to: "\.less$"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        dql:
            numeric_functions:
                year: Ferus\TransactionBundle\DQL\Year
                month: Ferus\TransactionBundle\DQL\Month
                day: Ferus\TransactionBundle\DQL\Day
                sum: Ferus\TransactionBundle\DQL\Sum
                if: Ferus\EventBundle\DQL\IfFunction
                nullif: Ferus\EventBundle\DQL\NullIf
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true

# Swiftmailer Configuration
swiftmailer:
    default_mailer: default
    mailers:
        default:
            transport: "%mailer_transport%"
            host:      "%mailer_host%"
            username:  "%mailer_user%"
            password:  "%mailer_password%"
            spool:     { type: memory }
        aws1:
            transport: "smtp"
            port: 587
            encryption: tls
            disable_delivery: true
            host:      "%mailer_aws1_host%"
            username:  "%mailer_aws1_user%"
            password:  "%mailer_aws1_password%"
        aws2:
            transport: "smtp"
            port: 587
            encryption: tls
            disable_delivery: true
            host:      "%mailer_aws2_host%"
            username:  "%mailer_aws2_user%"
            password:  "%mailer_aws2_password%"
        aws3:
            transport: "smtp"
            port: 587
            encryption: tls
            disable_delivery: true
            host:      "%mailer_aws3_host%"
            username:  "%mailer_aws3_user%"
            password:  "%mailer_aws3_password%"

# FOS User Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Ferus\UserBundle\Entity\User
    from_email:
        address:        bde@edu.esiee.fr
        sender_name:    BDE ESIEE Paris

# FOS Rest Configuration
fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        view_response_listener: 'force'
        formats:
            json : true
    routing_loader:
        default_format: json
        include_format: false

# Bootstrap Configuration
braincrafted_bootstrap:
    less_filter: less
    jquery_path: %kernel.root_dir%/../vendor/jquery/jquery/jquery-2.1.1.min.js
    output_dir: bootstrap
    auto_configure:
        assetic: true
        twig: true
        knp_menu: false
        knp_paginator: true

# JMS Configuration
jms_di_extra:
    locations:
        all_bundles: false
        bundles: [FerusStudentBundle, FerusAccountBundle, FerusSellerBundle, FerusTransactionBundle]
        directories: ["%kernel.root_dir%/../src"]
    automatic_controller_injections:
        properties:
            request: "@request"
            router: "@router"
            em: @doctrine.orm.entity_manager
            paginator: @knp_paginator
            flash: @braincrafted_bootstrap.flash

# Paginator Configuration
knp_paginator:
    page_range: 7
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true

# API Doc Configuration
nelmio_api_doc:
    name: Documentation de l'API FairPay
    sandbox:
        accept_type: null

        body_format:
            formats: []

        request_format:
            method: accept_header
            formats:
                json: application/json


# DoctrineExtensionBundle Configuration
stof_doctrine_extensions:
    orm:
        default:
            blameable: true
            timestampable: true
            softdeleteable: true